/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.kwesidev.paygate;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
       
        assertNotNull("hello", "app should have a greeting");
    }
}
